### ISSUE TITLE
Handle batch request timeout failures gracefully

### ISSUE THREAD

**Issue by benjamingr** [wildbit/postmark-dotnet#33]
When we try to send a batch of 500 messages through Postmark.Net we get a "A task was canceled" failure.

My guess is that this is a timeout error because the request takes too long. Sending a smaller batch (50) through postmark.net seems to work. 

I assume this is just the client throwing on a timeout - I think it would be great to not expose this behavior to end users and instead return a more detailed error message explaining that this indeed was a postmark API timeout issue - or conversely - to retry sending requests more than once before failing.

What do you think? 

Attached stack trace:

```
error A task was canceled. ; 
 A task was canceled. ======>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PostmarkDotNet.PCL.PostmarkClientBase.<ProcessRequestAsync>d__2`2.MoveNext() in c:\projects\postmark-dotnet\src\Postmark.PCL\PostmarkClientBase.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PostmarkDotNet.PostmarkClient.<SendMessagesAsync>d__3.MoveNext() in c:\projects\postmark-dotnet\src\Postmark.PCL\PostmarkClient.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PostmarkDotNet.PostmarkClientExtensions.<SendMessagesAsync>d__4.MoveNext() in c:\projects\postmark-dotnet\src\Postmark.PCL\PostmarkClientExtensions.cs:line 44
```

**Comment by benjamingr** [comment]
This is actually worse since postmark _did_ send these emails.

**Comment by atheken** [comment]
@benjamingr Have you seen this more than once? Can you tell me what the Exception type that was thrown was? 

If it was a TimeoutException, this could be due to any number of reasons, but I if the messages were sent, then I would expect it to (probably) be the following scenario:

1. You POST to the API using the client.
2. We accept and process the POST body (sending the emails).
3. The TCP connection is reset somewhere along the way.
4. We attempt to send a response, but the connection is gone. 
6. The client waits for the response, but it will timeout because the TCP connection has already been closed.

If this was the scenario, there's really nothing we can do, other than *maybe* producing an exception that says "Your messages might have been accepted by our API, go check." Without more context, it's going to be hard to know if this is the issue, and how frequently this is creating a "false negative" in the .net client.

**Comment by benjamingr** [comment]
Hi sorry for the lack of response - not sure what I did at that point!
