### ISSUE TITLE
Error parsing 'To': Illegal email mailbox 'name-lastname' in address 'name-lastname@hotmail.com'

### ISSUE THREAD

**Issue by erzki** [wildbit/postmark-dotnet#53]
We get this error when sending e-mail to valid e-mail adress. name-lastname@hotmail.com
Do you know if this is a postmark-dotnet issue or Postmark issue?

```
PostmarkDotNet.Exceptions.PostmarkValidationException: Error parsing 'To': Illegal email mailbox 'sanna-​lindgren' in address 'sanna-​lindgren@hotmail.com'.
   at PostmarkDotNet.PostmarkClientBase.<ProcessRequestAsync>d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PostmarkDotNet.PostmarkClient.<SendMessageAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bokio.Export.Mailing.MailHelper.<SendWithPostmark>d__2.MoveNext() in d:\a\1\s\Bokio.Export\Bokio.Export\Bokio.Export\Mailing\MailHelper.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bokio.Export.Controllers.MailController.<SendInvoice>d__16.MoveNext() in d:\a\1\s\Bokio.Export\Bokio.Export\Bokio.Export\Controllers\MailController.cs:line 277
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
```

**Comment by atheken** [comment]
@erzki, which version of the postmark client are you using?

**Comment by Jameskmonger** [comment]
I've just encountered a similar issue sending emails to (example) `Abcdef.Hijklmno@foo.net`
