### ISSUE TITLE
GetInboundMessagesAsync gives an PostmarkValidationException

### ISSUE THREAD

**Issue by xinix00** [wildbit/postmark-dotnet#88]
On one specific "query":
var events = await postmark.GetInboundMessagesAsync(0, 100, "an-emailaddress@something.com", null, null);

I get:
Exception has occurred: CLR/PostmarkDotNet.Exceptions.PostmarkValidationException
Exception thrown: 'PostmarkDotNet.Exceptions.PostmarkValidationException' in System.Private.CoreLib.dll
   at PostmarkDotNet.PostmarkClientBase.<ProcessRequestAsync>d__13`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PostmarkDotNet.PostmarkClientBase.<ProcessNoBodyRequestAsync>d__14`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PostmarkDotNet.PostmarkClient.<GetInboundMessagesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DirectCode.Module.Admin.Queries.MailInQuery.<ExecuteAsync>d__3.MoveNext() in ...

I don't have it on other "from addresses", but on one specific I get this as a result. You can test on our account, if you mail me at d.haas@directcode.com, and I will show you how to get this failure.

Kind regards,

Derek den Haas

**Comment by vladsandu** [comment]
@xinix00 sorry for the delay in replying here and thank you for this report.

We would be happy to investigate this further. To better facilitate communication, please [contact our Customer Support team](https://postmarkapp.com/contact) with a link to this issue and we will look into this shortly after.

**Comment by vladsandu** [comment]
I’m closing this issue because it has been inactive for a few months and is currently not reproducible in the latest version of the library.

Please reopen if you still encounter this issue with the [latest stable version](https://github.com/wildbit/postmark-dotnet/releases).

Thank you!
